version: '3.2'
networks:
  kek:
    driver: bridge

services:
  code:
    image: "src"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:8000
    environment:
      - BASE_ADDRESS="185.189.14.105"
      - PORT=80